// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice.itemattributes;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

public class CatalogNumberList implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "CatalogNumberListElement")
	@Order(value=0)
	public List<String> catalogNumberListElement;	
	
    
}