// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice.itemattributes;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import com.amazon.webservices.awsecommerceservice.itemattributes.languages.Language;
import java.util.List;

public class Languages implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Language")
	@Order(value=0)
	public List<Language> language;	
	
    
}